// Debug script để kiểm tra session data
// Chạy script này để debug session data

console.log('🔍 Debug Session Data...')
console.log('')
console.log('📋 Checklist để debug registration flow:')
console.log('')
console.log('1. Kiểm tra Database:')
console.log('   - Chạy database-schema.sql để thêm cột step')
console.log('   - Kiểm tra bảng bot_sessions có cột step chưa')
console.log('')
console.log('2. Kiểm tra Session Data:')
console.log('   - User nhập tên: session.data.name = "Đinh Khánh Tùng"')
console.log('   - User nhập phone: session.data.phone = "0982581222"')
console.log('   - Session step phải chuyển từ "name" -> "phone" -> "location"')
console.log('')
console.log('3. Kiểm tra Message Flow:')
console.log('   - handleNameStep: gửi "Họ tên: ${text.trim()}" với text = tên')
console.log('   - handlePhoneStep: gửi "SĐT: ${phone}" với phone = số điện thoại')
console.log('   - Không được gửi message "Họ tên:" khi đang ở step phone')
console.log('')
console.log('4. Vấn đề có thể xảy ra:')
console.log('   - Session data bị ghi đè')
console.log('   - Có nhiều message được gửi cùng lúc')
console.log('   - Logic xử lý step bị lỗi')
console.log('   - Anti-spam system can thiệp')
console.log('')
console.log('5. Cách debug:')
console.log('   - Thêm console.log vào handleNameStep và handlePhoneStep')
console.log('   - Kiểm tra session data trước và sau mỗi step')
console.log('   - Kiểm tra message nào được gửi')
console.log('')
console.log('🎯 Kết luận:')
console.log('Vấn đề là bot hiển thị "Họ tên: 0982581222" thay vì "SĐT: 0982581222"')
console.log('Có thể do session data bị lỗi hoặc logic xử lý step bị sai')
